from . import hr
from . import hr_contract
from . import hr_inputs
from . import hr_payslips
from . import hr_payslip_cron
from . import loan
from . import hr_staff_advance
from . import res_config_settings
from . import hr_location
from . import hr_attendance_ext
